<a href="https://colab.research.google.com/github/SalgadoHUB/image_processing_introduction/blob/main/Pr%C3%A1ctica1_Introduccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 1: Introducción a Colab, Numpy, OpenCV


Python es un lenguaje de programación de propósito general ampliamente utilizado en ciencia y tecnología, y por lo general se utiliza junto con algunas de sus librerías (numpy, pandas, matplotlib). en esta práctica haremos una breve introducción a las herramientas que vamos a usar en la asignatura.
En concreto, aprenderemos:

* Python básico, entorno Colab.
* Introducción a Numpy
* Visualización de variables (Matplotlib, OpenCv

Este guión de prácticas esta escrito como un cuaderno de Colab. Empezaremos haciendo una introducción a este entorno de trabajo.

## Colab y Python básico
Podemos abrir Colab desde nuestro Drive, o también en este enlace:

http://colab.research.google.com/github/googlecolab/

Si disponemos de una cuenta de Github, podemos sustituir "googlecolab" por nuestro usuario, y ejecutaremos nuestros cuadernos almacenados en Git.

En colab tenemos celdas de texto y celdas de código. A la izquierda de las celdas de código tenemos un botón con el símbolo ">". Si lo apretamos se ejecutará el código de la celda, y el resultado nos aparecerá debajo. Se puede cambiar el código y volver a ejecutar el código modificado. Alternativamente, también se puede apretar "Shift" + "Enter" simultaneamente para ejecutar la celda activa.

Este cuaderno pretende ser una guía de lo que vamos a ver en clase. Puedes ir leyendo el código tratando de entender qué resultado vamos a entender, o puedes ir escribiendo en un tu cuaderno las mismas órdenes. Se recomienda no "copiar y pegar" directamente, porque el objetivo es aprender.
As you work through this tutorial, look at the code in each cell, and try to predict its output before you run it! Then, run the cell and check your understanding. You can also try to modify the code and observe the effect of your changes.

### Tipos de variables
No es necesario definir las variables previamente.

In [1]:
x = 3
print(x, type(x))

3 <class 'int'>


In [3]:
y = 2.5
print(y, type(y))

<class 'float'>


In [2]:
print(x + 1)   # Suma
print(x - 1)   # Resta
print(x * 2)   # Multiplicación
print(x ** 2)  # Potencia

4
2
6
9


In [4]:
x += 1
print(x)
x *= 2
print(x)

4
8


### Cadenas de texto

In [5]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))
hw = hello + ' ' + world  # String concatenation
print(hw)

hello 5
hello world


### Listas
Las Listas en Python son el equivalente a arrays (con alguna diferencia)

In [6]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2]) # Las posiciones se empiezan a contar en "0"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

xs.append('bar') # Add a new element to the end of the list
print(xs)

x = xs.pop()     # Remove and return the last element of the list
print(x, xs)


[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

### Diccionarios
Los diccionarios almacenan pares (clave, valor). Son útiles para ordenar variables.

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

### Bucles
En los Bucles de Python, la indexación (tabulación) es muy importante.

In [7]:
x = -15

if x == 0:
    print(x, "is zero")
elif x > 0:
    print(x, "is positive")
elif x < 0:
    print(x, "is negative")
else:
    print(x, "is unlike anything I've ever seen...")

-15 is negative


In [8]:
for N in [2, 3, 5, 7]:
    print(N, end=' ') # print all on same line

2 3 5 7 

Es usual utilizar "range" para definir el rango del bucle for. Nótese que se comienza a contar en 0, y el límite superior de "range" queda fuera del bucle.

In [10]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


Se pueden hacer bucles para recorrer listas, independientemente del tipo de variables que contengan.

In [12]:
animals = ['gato', 'perro', 'mono']
for animal in animals:
    print(animal)

gato
perro
mono


También existen bucles "while":

In [13]:
i = 0
while i < 10:
    print(i, end=' ')
    i += 1

0 1 2 3 4 5 6 7 8 9 

También es usual ir rellenando listas dentro de un bucle. En este caso, tenemos que generar antes la lista vacía.

In [14]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


Otra forma de escribir lo mismo, en formato "pythonizado":

In [15]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


### Funciones
Si hay una parte de código que se repite asiduamente, podemos definir funciones (con argumentos) y llamarlas cuando nos convenga.
La forma de hacerlo es la siguiente:

In [16]:
def sign(x):
    if x > 0:
        return 'positivo'
    elif x < 0:
        return 'negativo'
    else:
        return 'cero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


## Introducción a Numpy
Numpy es una librearía para el cálculo numérico, que imita el funcionamiento de Matlab.
Para usarla primero tenemos que importarla.

In [18]:
import numpy as np

In [19]:
a = np.array([1, 2, 3])  # Create a rank 1 array

In [20]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [21]:
b = np.array([[1,2],[3,4]])   # Create a rank 2 array
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


Generación de matrices especiales

In [22]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)
c = np.full((2,2), 7) # Create a constant array
print(c)
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [26]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.00472163 0.82925284]
 [0.05694106 0.0653712 ]]




Numpy tiene dos funciones muy útiles para la generación de secuencias de números: arange linspace.

La función arange  tiene tres argumentos: valor inicial, valor final (intervalo semiabierto) y paso entre valores. Si no se especifica el paso, el salto por defecto es 1.

La función linspace es similar, pero en vez de especificar el paso se indica el número de elementos que debe tener el array.


In [27]:
f = np.arange(10,50,5)   # array de 10 a 50 en intervalos de 5. Acabará en 45, y no en 50
print(f)

[10 15 20 25 30 35 40 45]


In [28]:
g = np.linspace(0., 1., num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [29]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [30]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

Valores lógicos en arrays

In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [32]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


In [ ]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

# Get the index of the maximum element in a
print(np.argmax(a))

# Get the index of the minimum element in a
# (this array has two elements with the maximum value -
# only one index is returned)
print(np.argmin(a))

# Get sorted list of indices
print(np.argsort(a))

# Get sorted list of indices in descending order
# [::-1] is a special slicing index that returns the reversed list
print(np.argsort(a)[::-1])

# Get indices of elements that meet some condition
# this returns a tuple, the list of indices is the first entry
# so we use [0] to get it
print(np.where(a > 5)[0])

# Get indices of elements that meet some condition
# this example shows how to get the index of *all* the max values
print(np.where(a >= a[np.argmax(a)])[0])

Vectorización
Es importante evitar los bucles for cuando se hacen cálculos.

In [33]:
a = np.random.random(100000000)

In [34]:
%%time
x = 0
for element in a:
  x = x + element

CPU times: user 20.3 s, sys: 0 ns, total: 20.3 s
Wall time: 21.1 s


In [35]:
%%time
x = np.sum(a)

CPU times: user 145 ms, sys: 0 ns, total: 145 ms
Wall time: 154 ms


In [36]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [37]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [38]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [39]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Para hacer producto vectorial, utilizamos "dot()"

In [41]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


Sigue el tutorial en:
https://colab.research.google.com/github/ffund/ml-notebooks/blob/master/notebooks/1-python-numpy-tutorial.ipynb#scrollTo=6e8eaf91-4f6a-4c82-b2a9-b4ab9c840554